---
language: go
go:
- 1.3.3
env:
  global:
  - PATH=$HOME/bin:$HOME/gopath/bin:$PATH
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=modcloth-public-travis-artifacts
  - MITHRIL_PG_URI='postgres://postgres@localhost?sslmode=disable'
  - MITHRIL_PG_DB_NAME='postgres'
  - MITHRIL_PG_USER='postgres'
  - secure: |-
      FJHd6ppu+tmqK22fOWa+muolpMkkQt+ycz3ytnw7Nar8bn8UMOGGE5NvRF4r
      Zg+qt5w44zwijAV0RKehSVu1gJaY3VuKq2JgHpmveuWgxPD92fnP2FZcc5Dv
      WV7HtxvJdb9BU1dfJsMy4Tf3SF12B/lpaC0t103GpAoPSUIXw70=
  - secure: |-
      ntSya4NnAwV+cRdfkLphr2VQALklQHgGZC2LV6VHPjsChEMI5Sh32yEB/Pv/
      7qKZ3bWfsAN8u5s7mpySP1xRtl+NX+ATjQkhmb1z/gSL57J3XhgCQwEqZNWW
      aSbgocDcVA2CjNhiMI2ze1FSr7rXptAyGu7sLJUXXU8ftALFhRs=
  - secure: |-
      aeTbhomNFMK7gc8byHFcZDbsfDYpTUoSu1qxhraCVxzxcG9txoCPwMEgmVeh
      36env+3ioGxFUwfMtT3qrezQ13jeHlgRyXxnnsPUTC/wMMhVlvPYXsakUTOY
      DK9Crr8ZZvzHQ+6QLtU47xLqL8GKM/x1mzDAVy7QzqN2c57l168=
  matrix:
  - MITHRIL_PG_ENABLED='true' GO_TAG_ARGS=''
  - MITHRIL_PG_ENABLED='false' GO_TAG_ARGS='-tags nil'
services:
- rabbitmq
before_install:
- mkdir -p $HOME/bin
- pushd $HOME/bin
- sudo rabbitmq-plugins enable rabbitmq_management
- curl http://guest:guest@localhost:15672/cli/rabbitmqadmin > $HOME/bin/rabbitmqadmin
- chmod +x $HOME/bin/rabbitmqadmin
- popd
- go get -x github.com/meatballhat/deppy
install: make build
script: make golden
addons:
  artifacts:
    debug: '1'
    key:
      secure: jyc2YmclTdtcdi0vrzNDP/90UeZ6PwePVyorH8Hob3FvbJaNULThCG/jOsEfzEeTR6V0Utcz77xpHc79NcMadymva+0CeIhg0jz4aC+EoyC3LtU7hGZCdMJVAdnGCUvWdFZSmBh9VQlK6sH2m8q0U44R67QwXXdZWkNXVDFGMtk=
    secret:
      secure: cqghxNJC7kcwM/QS2/7MaPso7nPJIy66fc/uj2koqsX9CdIuW3mQtxMyqe2A//LR/GEVTl43cBIR9n2JZMnD+3uW9lN+/fvAUY0z1MBhU9fn+cb6YodF/Su67UgcBaYbROQFUTPF3p1ePvozsxSua0q4ZdR/wvaC8lqPUMTl+Dg=
notifications:
  email:
    recipients:
    - github+mithril@modcloth.com
