---
language: go
env:
  global:
  - GOPATH_DEST=$HOME/gopath/src/github.com/modcloth-labs
  - MITHRIL_PG_URI='postgres://postgres@localhost?sslmode=disable'
  - MITHRIL_PG_DB_NAME='postgres'
  - MITHRIL_PG_USER='postgres'
services:
- rabbitmq
install:
- mkdir -p $GOPATH_DEST
- ln -sv $TRAVIS_BUILD_DIR $GOPATH_DEST/mithril
script: make golden
