---
language: go
env:
  global:
  - PATH=$HOME/bin:$PATH
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=travis-artifacts-modcloth
  - GOPATH_DEST=$HOME/gopath/src/github.com/modcloth-labs
  - MITHRIL_PG_URI='postgres://postgres@localhost?sslmode=disable'
  - MITHRIL_PG_DB_NAME='postgres'
  - MITHRIL_PG_USER='postgres'
  - secure: ! 'bQqPFIEGmcrIvaz0woB1WhzMebkBdMU90A+N16Qmgmwni1hAwXbbZfQFT8S1

      bWyCgvpVmhdMTMjM4Uqvz3JRL+6/nKoq0X88LYLGmKF34cXt2i8lbNOxkhSl

      LWhP8xWxOZn9NA/a55kZL/BpYxIc4E8mu18sIQxE1jzHg13c6+o='

  - secure: ! 'DnIbKKDlg+CJL5Dcb4Q7pTz++vdzLd4aHKULOWTM7CoXIBuj8pbAjEB1Jg3r

      KJQXY80fv45F4hR/ct50nkXySPIZRgVNcG+Q6Yq4urYkBE0YodcAPCytlheD

      vE8yL3T8qKypsQHg3PDF3ShVOgdyzWozKRRbDluWYsjac1puSEU='

  - secure: ! 'hye7R3WnaQRUwtHh0t+JThpwwuXux/3aBc7DmovWAt99zfGm8MhNtU6KAssK

      wSJcw+iWoRsRZ0r8TYzZxZDnRLnfIOgK3oceqEGhGaaOxP2RGiNdveqxwnjT

      HaD9pTqPeK7y2tsuLUhBPk1Q0OYp3TXZFaxwFI9JCjnoYw4sg5o='
  matrix:
  - MITHRIL_PG_ENABLED='true' GO_TAG_ARGS='-tags pg'
  - MITHRIL_PG_ENABLED='false' GO_TAG_ARGS=''
services:
- rabbitmq
before_install:
- sudo rabbitmq-plugins enable rabbitmq_management
- curl http://guest:guest@localhost:15672/cli/rabbitmqadmin > $HOME/bin/rabbitmqadmin
- mkdir -p $HOME/bin
- pushd $HOME/bin
- curl -s -O https://raw.github.com/modcloth-labs/travis-buddy/v0.1.0/tb
- chmod +x tb
- popd
- tb setup-aws
- if tb nopr ; then
    tb install-travis-artifacts ;
  fi
install:
- if tb nopr ; then
    cd $TRAVIS_BUILD_DIR && make build ;
  else
    echo Building pull requests for mithril no worky ;
  fi
script:
- if tb nopr ; then
    cd $TRAVIS_BUILD_DIR && make golden ;
  else
    echo Building pull requests for mithril no worky ;
  fi
after_success:
- if tb nopr ; then
    tb upload-go-artifacts --encrypt ;
    tb upload-artifact artifacts/binaries/$(go env GOOS)/$(go env GOARCH)/mithril/$TRAVIS_COMMIT/
      --encrypt ;
  fi
notifications:
  email:
    recipients:
      - flintknappers+mithril@modcloth.com
