---
language: go
env:
  global:
  - PATH=$HOME/bin:$PATH
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=modcloth-public-travis-artifacts
  - GOPATH_DEST=$HOME/gopath/src/github.com/modcloth-labs
  - MITHRIL_PG_URI='postgres://postgres@localhost?sslmode=disable'
  - MITHRIL_PG_DB_NAME='postgres'
  - MITHRIL_PG_USER='postgres'
  - secure: ! 'FJHd6ppu+tmqK22fOWa+muolpMkkQt+ycz3ytnw7Nar8bn8UMOGGE5NvRF4r

      Zg+qt5w44zwijAV0RKehSVu1gJaY3VuKq2JgHpmveuWgxPD92fnP2FZcc5Dv

      WV7HtxvJdb9BU1dfJsMy4Tf3SF12B/lpaC0t103GpAoPSUIXw70='
  - secure: ! 'ntSya4NnAwV+cRdfkLphr2VQALklQHgGZC2LV6VHPjsChEMI5Sh32yEB/Pv/

      7qKZ3bWfsAN8u5s7mpySP1xRtl+NX+ATjQkhmb1z/gSL57J3XhgCQwEqZNWW

      aSbgocDcVA2CjNhiMI2ze1FSr7rXptAyGu7sLJUXXU8ftALFhRs='
  - secure: ! 'aeTbhomNFMK7gc8byHFcZDbsfDYpTUoSu1qxhraCVxzxcG9txoCPwMEgmVeh

      36env+3ioGxFUwfMtT3qrezQ13jeHlgRyXxnnsPUTC/wMMhVlvPYXsakUTOY

      DK9Crr8ZZvzHQ+6QLtU47xLqL8GKM/x1mzDAVy7QzqN2c57l168='
  matrix:
  - MITHRIL_PG_ENABLED='true' GO_TAG_ARGS='-tags full'
  - MITHRIL_PG_ENABLED='false' GO_TAG_ARGS=''
services:
- rabbitmq
before_install:
- mkdir -p $HOME/bin
- pushd $HOME/bin
- sudo rabbitmq-plugins enable rabbitmq_management
- curl http://guest:guest@localhost:15672/cli/rabbitmqadmin > $HOME/bin/rabbitmqadmin
- chmod +x $HOME/bin/rabbitmqadmin
- curl -s -O https://raw.github.com/modcloth-labs/travis-buddy/master/tb
- chmod +x tb
- popd
- tb setup-aws
- if tb nopr ; then
    tb install-travis-artifacts ;
  fi
install: cd $TRAVIS_BUILD_DIR && make build
script: cd $TRAVIS_BUILD_DIR && make golden
after_success:
- if tb nopr && [ "$GO_TAG_ARGS" == '-tags full' ] ; then
    tb upload-go-artifacts --public ;
  fi
notifications:
  email:
    recipients:
    - github+mithril@modcloth.com
