language: go
go:
- 1.3.3
env:
  global:
  - PATH=$HOME/bin:$HOME/gopath/bin:$PATH
  - MITHRIL_PG_URI='postgres://postgres@localhost?sslmode=disable'
  - MITHRIL_PG_DB_NAME='postgres'
  - MITHRIL_PG_USER='postgres'
  matrix:
  - MITHRIL_PG_ENABLED='true' GO_TAG_ARGS=''
  - MITHRIL_PG_ENABLED='false' GO_TAG_ARGS='-tags nil'
services:
- rabbitmq
before_install:
- mkdir -p $HOME/bin
- pushd $HOME/bin
- sudo rabbitmq-plugins enable rabbitmq_management
- curl http://guest:guest@localhost:15672/cli/rabbitmqadmin > $HOME/bin/rabbitmqadmin
- chmod +x $HOME/bin/rabbitmqadmin
- popd
- go get -x github.com/meatballhat/deppy
install: make build
script: make golden
after_success:
- mkdir -p build
- cp -v ~/gopath/bin/mithril-server build/
addons:
  artifacts:
    debug: '1'
    bucket: modcloth-public-travis-artifacts
    key:
      secure: jyc2YmclTdtcdi0vrzNDP/90UeZ6PwePVyorH8Hob3FvbJaNULThCG/jOsEfzEeTR6V0Utcz77xpHc79NcMadymva+0CeIhg0jz4aC+EoyC3LtU7hGZCdMJVAdnGCUvWdFZSmBh9VQlK6sH2m8q0U44R67QwXXdZWkNXVDFGMtk=
    secret:
      secure: cqghxNJC7kcwM/QS2/7MaPso7nPJIy66fc/uj2koqsX9CdIuW3mQtxMyqe2A//LR/GEVTl43cBIR9n2JZMnD+3uW9lN+/fvAUY0z1MBhU9fn+cb6YodF/Su67UgcBaYbROQFUTPF3p1ePvozsxSua0q4ZdR/wvaC8lqPUMTl+Dg=
    on:
      go: 1.3.3
      condition: "$MITHRIL_PG_ENABLED = true"
notifications:
  email:
    recipients:
    - github+mithril@modcloth.com
deploy:
  provider: releases
  api_key:
    secure: JdPZvNLhs4/CabhvSe8/eyBCU+lAvuGp6wC+ndVpqr5+Hv9TIzuxFXvJwaT95TC71Lwf0//GlrDooi08z+t0+VVKGBfp4IlPFuqWMWiRne+/0ckpzDnNch/1AXvgIaTh281vBXpvDjBvGU2oKObVyLMPtpMlcWFNBmqb7JeeM+M=
  file: build/mithril-server
  on:
    repo: modcloth-labs/mithril
    tags: true
    all_branches: true
