---
language: go
notifications:
  email:
    recipients:
      - flintknappers+mithril@modcloth.com
env:
  global:
  - GOPATH_DEST=$HOME/gopath/src/github.com/modcloth-labs
  - MITHRIL_PG_URI='postgres://postgres@localhost?sslmode=disable'
  - MITHRIL_PG_DB_NAME='postgres'
  - MITHRIL_PG_USER='postgres'
  matrix:
  - MITHRIL_PG_ENABLED=true
  - MITHRIL_PG_ENABLED=false
services:
- rabbitmq
install:
- mkdir -p $GOPATH_DEST
- ln -sv $TRAVIS_BUILD_DIR $GOPATH_DEST/mithril
script:
- ! 'if [[ "$MITHRIL_PG_ENABLED" == "true" ]] ; then
       make golden ;
     else
       make golden GO_TAG_ARGS="" ;
     fi'
